import type { Metadata } from "next";
import {Poppins, Montserrat, Outfit} from 'next/font/google'
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700"],
  variable: "--font-poppins",
})

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700"],
  variable: "--font-montserrat",
});

const outfit = Outfit ({
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700"],
  variable: "--font-outfit",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${montserrat.variable} ${outfit.variable} h-full antialiased`}
      >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
